export type cache = { [key: string]: { [key: string]: string } };
export { yearGender } from "./yearGender";
export { year } from "./year";
export { month } from "./month";
export { day } from "./day";
export { hour } from "./hour";
export { age } from "./age";
export { yearKyeMe } from "./yearKyeMe";
export { kyePar } from "./kyePar";
export { yearBapMe } from "./yearBapMe";
export { yearBapPar } from "./yearBapPar";
